ln -s ~/dotfiles/.bashrc ~/.bashrc
ln -s ~/dotfiles/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/.gitignore_global ~/.gitignore_global
ln -s ~/dotfiles/.irssi ~/.irssi
ln -s ~/dotfiles/irssi-colors-solarized ~/irssi-colors-solarized
ln -s ~/dotfiles/.muttrc ~/.muttrc
ln -s ~/dotfiles/.oh-my-zsh ~/.oh-my-zsh
ln -s ~/dotfiles/.profile ~/.profile
ln -s ~/dotfiles/.zshrc ~/.zshrc
ln -s ~/dotfiles/.vimrc ~/.vimrc
ln -s ~/dotfiles/.vim ~/.vim
ln -s ~/dotfiles/.zlogin ~/.zlogin
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/.tmuxinator ~/.tmuxinator
ln -s ~/dotfiles/.bash_login ~/.bash_login
ln -s ~/dotfiles/.offlineimaprc ~/.offlineimaprc
ln -s ~/dotfiles/.goobookrc ~/.goobookrc
ln -s ~/dotfiles/.todo ~/.todo
